version: 2
project_name: client

builds:
  - id: client
    dir: ./client
    main: ./cmd/client
    goos:  [linux, darwin, windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: binaries
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Le-BlitzZz
    name:  blockchain-auth-app
